### ISSUE TITLE
Feature request: Display X number entries on load

### ISSUE THREAD

**Issue by daltonrooney** [Hestabit/craft-ajaxinate#7]
Currently the plugin only displays additional entries when clicking the "load more" link. In that case, I have to already write a separate template to display the first X number of entries. Then the "load more" button runs a new query to display additional entries.

Wouldn't it be easier if I could just show the first X number of entries using the craft.craftAjaxinate.render tag? Then I only need to think about one query and simply append new results to the current list.

**Comment by anshul321** [comment]
Hi @daltonrooney , we are actually planning to add this feature in the next release. We are currently planning to make the start date dynamic so that the admin can easily select the field from which he/she wants to fetch the start date.

Will let you know once we are about to release the new update.

Thanks :)

**Comment by anshul321** [comment]
Hi @daltonrooney , we can surely add this feature in the next release.  We are planning to release this feature by next week as we have a lot of future development planned for the plugin.

Thanks for the suggestion.

**Comment by anshul321** [comment]
Hi @daltonrooney , we have released a new version of the plugin which allows the developer to manage the configuration of the plugin on the template level. The above-mentioned feature has been added to the plugin as well.
Kindly update the plugin and share your valuable feedback. 

Thanks & Regards
